import { PERMISSIONS, PermissionType } from './permissions.js';

export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  HOTEL_ADMIN: 'HOTEL_ADMIN',
  MANAGER: 'MANAGER',
  RECEPTIONIST: 'RECEPTIONIST',
  HOUSEKEEPING_MANAGER: 'HOUSEKEEPING_MANAGER',
  HOUSEKEEPING_STAFF: 'HOUSEKEEPING_STAFF',
  MAINTENANCE_MANAGER: 'MAINTENANCE_MANAGER',
  MAINTENANCE_STAFF: 'MAINTENANCE_STAFF',
  RESTAURANT_MANAGER: 'RESTAURANT_MANAGER',
  RESTAURANT_STAFF: 'RESTAURANT_STAFF',
  ACCOUNTANT: 'ACCOUNTANT',
} as const;

export type SystemRoleType = typeof SYSTEM_ROLES[keyof typeof SYSTEM_ROLES];

// Helper to define permissions mapped to standard roles
export const ROLE_PERMISSIONS: Record<SystemRoleType, PermissionType[]> = {
  SUPER_ADMIN: [], // Super Admins bypass permissions via code checks
  
  HOTEL_ADMIN: [
    ...Object.values(PERMISSIONS.USERS),
    ...Object.values(PERMISSIONS.ROLES),
    ...Object.values(PERMISSIONS.ROOMS),
    ...Object.values(PERMISSIONS.GUESTS),
    ...Object.values(PERMISSIONS.RESERVATIONS),
    ...Object.values(PERMISSIONS.BILLING),
    ...Object.values(PERMISSIONS.HOUSEKEEPING),
    ...Object.values(PERMISSIONS.MAINTENANCE),
    ...Object.values(PERMISSIONS.RESTAURANT),
    ...Object.values(PERMISSIONS.INVENTORY),
    ...Object.values(PERMISSIONS.EMPLOYEES),
    ...Object.values(PERMISSIONS.REPORTS),
    ...Object.values(PERMISSIONS.ANALYTICS),
    ...Object.values(PERMISSIONS.SYSTEM),
  ] as PermissionType[],

  MANAGER: [
    ...Object.values(PERMISSIONS.USERS),
    ...Object.values(PERMISSIONS.ROLES),
    ...Object.values(PERMISSIONS.ROOMS),
    ...Object.values(PERMISSIONS.GUESTS),
    ...Object.values(PERMISSIONS.RESERVATIONS),
    ...Object.values(PERMISSIONS.BILLING),
    ...Object.values(PERMISSIONS.HOUSEKEEPING),
    ...Object.values(PERMISSIONS.MAINTENANCE),
    ...Object.values(PERMISSIONS.RESTAURANT),
    ...Object.values(PERMISSIONS.INVENTORY),
    ...Object.values(PERMISSIONS.EMPLOYEES),
    ...Object.values(PERMISSIONS.REPORTS),
    ...Object.values(PERMISSIONS.ANALYTICS),
    ...Object.values(PERMISSIONS.SYSTEM),
  ] as PermissionType[],

  RECEPTIONIST: [
    ...Object.values(PERMISSIONS.USERS),
    ...Object.values(PERMISSIONS.ROLES),
    ...Object.values(PERMISSIONS.ROOMS),
    ...Object.values(PERMISSIONS.GUESTS),
    ...Object.values(PERMISSIONS.RESERVATIONS),
    ...Object.values(PERMISSIONS.BILLING),
    ...Object.values(PERMISSIONS.HOUSEKEEPING),
    ...Object.values(PERMISSIONS.MAINTENANCE),
    ...Object.values(PERMISSIONS.RESTAURANT),
    ...Object.values(PERMISSIONS.INVENTORY),
    ...Object.values(PERMISSIONS.EMPLOYEES),
    ...Object.values(PERMISSIONS.REPORTS),
    ...Object.values(PERMISSIONS.ANALYTICS),
    ...Object.values(PERMISSIONS.SYSTEM),
  ] as PermissionType[],

  HOUSEKEEPING_MANAGER: [
    ...Object.values(PERMISSIONS.USERS),
    ...Object.values(PERMISSIONS.ROLES),
    ...Object.values(PERMISSIONS.ROOMS),
    ...Object.values(PERMISSIONS.GUESTS),
    ...Object.values(PERMISSIONS.RESERVATIONS),
    ...Object.values(PERMISSIONS.BILLING),
    ...Object.values(PERMISSIONS.HOUSEKEEPING),
    ...Object.values(PERMISSIONS.MAINTENANCE),
    ...Object.values(PERMISSIONS.RESTAURANT),
    ...Object.values(PERMISSIONS.INVENTORY),
    ...Object.values(PERMISSIONS.EMPLOYEES),
    ...Object.values(PERMISSIONS.REPORTS),
    ...Object.values(PERMISSIONS.ANALYTICS),
    ...Object.values(PERMISSIONS.SYSTEM),
  ] as PermissionType[],

  HOUSEKEEPING_STAFF: [
    ...Object.values(PERMISSIONS.USERS),
    ...Object.values(PERMISSIONS.ROLES),
    ...Object.values(PERMISSIONS.ROOMS),
    ...Object.values(PERMISSIONS.GUESTS),
    ...Object.values(PERMISSIONS.RESERVATIONS),
    ...Object.values(PERMISSIONS.BILLING),
    ...Object.values(PERMISSIONS.HOUSEKEEPING),
    ...Object.values(PERMISSIONS.MAINTENANCE),
    ...Object.values(PERMISSIONS.RESTAURANT),
    ...Object.values(PERMISSIONS.INVENTORY),
    ...Object.values(PERMISSIONS.EMPLOYEES),
    ...Object.values(PERMISSIONS.REPORTS),
    ...Object.values(PERMISSIONS.ANALYTICS),
    ...Object.values(PERMISSIONS.SYSTEM),
  ] as PermissionType[],

  MAINTENANCE_MANAGER: [
    ...Object.values(PERMISSIONS.USERS),
    ...Object.values(PERMISSIONS.ROLES),
    ...Object.values(PERMISSIONS.ROOMS),
    ...Object.values(PERMISSIONS.GUESTS),
    ...Object.values(PERMISSIONS.RESERVATIONS),
    ...Object.values(PERMISSIONS.BILLING),
    ...Object.values(PERMISSIONS.HOUSEKEEPING),
    ...Object.values(PERMISSIONS.MAINTENANCE),
    ...Object.values(PERMISSIONS.RESTAURANT),
    ...Object.values(PERMISSIONS.INVENTORY),
    ...Object.values(PERMISSIONS.EMPLOYEES),
    ...Object.values(PERMISSIONS.REPORTS),
    ...Object.values(PERMISSIONS.ANALYTICS),
    ...Object.values(PERMISSIONS.SYSTEM),
  ] as PermissionType[],

  MAINTENANCE_STAFF: [
    ...Object.values(PERMISSIONS.USERS),
    ...Object.values(PERMISSIONS.ROLES),
    ...Object.values(PERMISSIONS.ROOMS),
    ...Object.values(PERMISSIONS.GUESTS),
    ...Object.values(PERMISSIONS.RESERVATIONS),
    ...Object.values(PERMISSIONS.BILLING),
    ...Object.values(PERMISSIONS.HOUSEKEEPING),
    ...Object.values(PERMISSIONS.MAINTENANCE),
    ...Object.values(PERMISSIONS.RESTAURANT),
    ...Object.values(PERMISSIONS.INVENTORY),
    ...Object.values(PERMISSIONS.EMPLOYEES),
    ...Object.values(PERMISSIONS.REPORTS),
    ...Object.values(PERMISSIONS.ANALYTICS),
    ...Object.values(PERMISSIONS.SYSTEM),
  ] as PermissionType[],

  RESTAURANT_MANAGER: [
    ...Object.values(PERMISSIONS.USERS),
    ...Object.values(PERMISSIONS.ROLES),
    ...Object.values(PERMISSIONS.ROOMS),
    ...Object.values(PERMISSIONS.GUESTS),
    ...Object.values(PERMISSIONS.RESERVATIONS),
    ...Object.values(PERMISSIONS.BILLING),
    ...Object.values(PERMISSIONS.HOUSEKEEPING),
    ...Object.values(PERMISSIONS.MAINTENANCE),
    ...Object.values(PERMISSIONS.RESTAURANT),
    ...Object.values(PERMISSIONS.INVENTORY),
    ...Object.values(PERMISSIONS.EMPLOYEES),
    ...Object.values(PERMISSIONS.REPORTS),
    ...Object.values(PERMISSIONS.ANALYTICS),
    ...Object.values(PERMISSIONS.SYSTEM),
  ] as PermissionType[],

  RESTAURANT_STAFF: [
    ...Object.values(PERMISSIONS.USERS),
    ...Object.values(PERMISSIONS.ROLES),
    ...Object.values(PERMISSIONS.ROOMS),
    ...Object.values(PERMISSIONS.GUESTS),
    ...Object.values(PERMISSIONS.RESERVATIONS),
    ...Object.values(PERMISSIONS.BILLING),
    ...Object.values(PERMISSIONS.HOUSEKEEPING),
    ...Object.values(PERMISSIONS.MAINTENANCE),
    ...Object.values(PERMISSIONS.RESTAURANT),
    ...Object.values(PERMISSIONS.INVENTORY),
    ...Object.values(PERMISSIONS.EMPLOYEES),
    ...Object.values(PERMISSIONS.REPORTS),
    ...Object.values(PERMISSIONS.ANALYTICS),
    ...Object.values(PERMISSIONS.SYSTEM),
  ] as PermissionType[],

  ACCOUNTANT: [
    ...Object.values(PERMISSIONS.USERS),
    ...Object.values(PERMISSIONS.ROLES),
    ...Object.values(PERMISSIONS.ROOMS),
    ...Object.values(PERMISSIONS.GUESTS),
    ...Object.values(PERMISSIONS.RESERVATIONS),
    ...Object.values(PERMISSIONS.BILLING),
    ...Object.values(PERMISSIONS.HOUSEKEEPING),
    ...Object.values(PERMISSIONS.MAINTENANCE),
    ...Object.values(PERMISSIONS.RESTAURANT),
    ...Object.values(PERMISSIONS.INVENTORY),
    ...Object.values(PERMISSIONS.EMPLOYEES),
    ...Object.values(PERMISSIONS.REPORTS),
    ...Object.values(PERMISSIONS.ANALYTICS),
    ...Object.values(PERMISSIONS.SYSTEM),
  ] as PermissionType[],
};
